name: Trigger Deployment to Staging

on:
  push:
    branches:
      - main

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment to Staging
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/zhou1323/chaiGO/workflows/deploy-staging.yml/dispatches \
          -d '{"ref":"main"}'
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
